<?php

namespace AppBundle\Repository;

/**
 * HostelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HostelRepository extends \Doctrine\ORM\EntityRepository
{
}
