<?php

namespace AppBundle\Repository;

/**
 * ImageTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageTagRepository extends \Doctrine\ORM\EntityRepository
{
}
