<?php

namespace AppBundle\Repository;

/**
 * ArrivalMeanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArrivalMeanRepository extends \Doctrine\ORM\EntityRepository
{
}
