<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * HostelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HostelRepository extends EntityRepository
{
    public function search($searchTerm) {
        $em = $this->getEntityManager();
        $mapping = new ResultSetMappingBuilder($em);
        $mapping->addRootEntityFromClassMetadata('AppBundle\Entity\Hostel', 'h');

        $sql = "CALL search_hostels(?)";
        $query = $em->createNativeQuery($sql, $mapping);
        $query->setParameter(1, $searchTerm);

        return $query->getResult();
    }
}
