<?php

namespace AppBundle\Repository;

/**
 * ImageDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageDescriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
