<?php

namespace AppBundle\Repository;
use Gedmo\Sortable\Entity\Repository\SortableRepository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends SortableRepository
{
}
