<?php

namespace AppBundle\Repository;

/**
 * OtherServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtherServicesRepository extends \Doctrine\ORM\EntityRepository
{
}
