<?php

namespace AppBundle\Repository;

/**
 * PartOfTheHouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartOfTheHouseRepository extends \Doctrine\ORM\EntityRepository
{
}
