<?php

namespace AppBundle\Repository;

/**
 * HostelImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomImageRepository extends \Doctrine\ORM\EntityRepository
{
}
