# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  andorina.twig.country_extension:
    class: AppBundle\Twig\CountryExtension
    tags:
      - { name: twig.extension }
  andorina.twig.locale_extension:
    class: AppBundle\Twig\LocaleExtension
    tags:
      - { name: twig.extension }
  app.post_voter:
    class: AppBundle\Security\HostelVoter
    arguments: ['@security.access.decision_manager']
    public: false
    tags:
      - { name: security.voter }
  app.booking_voter:
    class: AppBundle\Security\BookingVoter
    arguments: ['@security.access.decision_manager']
    public: false
    tags:
      - { name: security.voter }
  app.directory_namer.hostel:
    class: AppBundle\Uploads\HostelDirectoryNamer
  app.form.registration:
    class: AppBundle\Form\RegistrationType
    tags:
      - { name: form.type, alias: app_user_registration }
  app.form.profile:
      class: AppBundle\Form\ProfileType
      tags:
        - { name: form.type, alias: app_user_profile }
  admin.hostel:
    class: AppBundle\Admin\HostelAdmin
    arguments: [~, AppBundle\Entity\Hostel, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Hostel }
  admin.room:
      class: AppBundle\Admin\RoomAdmin
      arguments: [~, AppBundle\Entity\Room, ~]
      tags:
        - { name: sonata.admin, manager_type: orm, label: Room }
  image.room:
    class: AppBundle\Admin\ImageAdmin
    arguments: [~, AppBundle\Entity\HostelImage, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Image }
  app.image:
    class: AppBundle\Entity\Image
    arguments: ['@liip_imagine.cache.manager']
  app.hostel.image:
      class: AppBundle\Entity\HostelImage
      arguments: ['@liip_imagine.cache.manager']